"""
Alembic env.py — integrado com pydantic-settings e SQLAlchemy.

Por que isso importa:
  - Em vez de hardcodar a DATABASE_URL aqui, lemos de Settings(),
    garantindo que a mesma fonte de verdade usada pela API seja usada
    pelas migrations. Trocar o banco é mudar uma variável de ambiente.
  - Suporta tanto modo offline (gera SQL puro) quanto online (aplica no banco).
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from main import Base, settings

# Configuração de logging do alembic.ini
config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Metadados dos modelos — o Alembic compara isso com o estado real do banco
# para gerar migrações autogenerated (alembic revision --autogenerate).
target_metadata = Base.metadata

# Sobrescreve a sqlalchemy.url do alembic.ini com o valor de pydantic-settings.
config.set_main_option("sqlalchemy.url", settings.database_url)


def run_migrations_offline() -> None:
    """
    Modo offline: gera um script SQL sem conectar ao banco.
    Útil para auditar migrações ou aplicá-las manualmente em produção.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Modo online: conecta ao banco e aplica as migrações diretamente.
    """
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
